name: Build Mac App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows you to manually run this workflow from GitHub

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build macOS App
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App-DMG
          path: dist/*.dmg
          retention-days: 7
